#How To Create Variable In TensorFlow 2.X

The **Variable()** **constructor** requires an initial value for the variable, which can be a Tensor of any type and shape. This initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.

***Syntax:***

tf.Variable(
initial_value=None, trainable=None, validate_shape=True, caching_device=None, name=None, variable_def=None, dtype=None, import_scope=None, constraint=None, synchronization=tf.VariableSynchronization.AUTO, aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None)



In [1]:
#Import TensorFlow
import tensorflow as tf

In [2]:
# # Create Tensor
tf.Variable(1)

a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [3]:
#Get Variable Name, Shape, Data Type & convert into NumpyArray
a.name

'Variable:0'

In [4]:
a.shape

TensorShape([4])

In [5]:
a.dtype

tf.int32

In [6]:
a.numpy()

array([1, 2, 3, 4], dtype=int32)

In [7]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [8]:
# Create TF using Integer, Float, String, Bool, Complex Number
t_f = tf.Variable([1.2,4.4,5,6])
t_f

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 4.4, 5. , 6. ], dtype=float32)>

In [9]:
t_s = tf.Variable(['a','b','c','d'])

t_b = tf.Variable([True, False])

t_cx = tf.Variable([3 + 4j])

In [10]:
# Create TF from Constant TensorFlow Variable
t_con = tf.constant([1,2,3,4])
t_con

tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [11]:
 # Create TF Variable with different shape
t_2d = tf.Variable([[2,3], [4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [12]:
t_2d_2 = tf.Variable([[2,3], [4,5]], shape=(2,2), dtype='float32')
t_2d_2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [13]:
a

tf.reshape(a, (2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [14]:
# Get Index of highest value
t_2d_2

tf.argmax(t_2d_2)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [15]:
# Viewed/convert as a tensor
a

tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [16]:
# Change/Assign new value to tensor
a.assign([4,6,2,8])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

**Assign Variable with anothe memory**


If you use a variable like a tensor in operations, you will usually operate on the backing tensor.

Creating new variables from existing variables duplicates the backing tensors. Two variables will not share the same memory.

In [17]:
a.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 16], dtype=int32)>