#Create Ones & Zeros

In TensorFlow 2.0, we can create Ones Tensor(every element in tensor are ones) in different ways using tf.ones() and tf.ones_like() and tf.ones_initializer()and we can create Zeros Tensor(every element in tensor are zeros) in different ways using tf.zeros() and tf.zeros_like() and tf.zeros_initializer().

```
# This is formatted as code
```



#Create Ones Tesnor using tf.ones()

Creates a tensor with all elements set to one (1)

Syntax:

tf.ones(shape, dtype=tf.dtypes.float32, name=None) -> Return Ones Tensor


In [1]:
# Import TensorFlow 2
import tensorflow as tf

# create ones tensor
ones_2dt = tf.ones((2,2), tf.float32)
ones_2dt

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

#Create Ones Tesnor using tf.ones_like()
Creates a tensor of all ones that has the same shape as the input

Syntax:

tf.ones_like(input, dtype=None, name=None) -> Return Ones Tensor


In [2]:
# create ones tensor from input

cont_2dt = tf.constant([[1,2,3],[4,5,6]])
cont_2dt

ones_2dt_from_cont = tf.ones_like(cont_2dt, tf.float32)
ones_2dt_from_cont

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

#Create Ones Tesnor using tf.ones_initializer() Initializer that generates tensors initialized to 1.

Initializers allow you to pre-specify an initialization strategy, encoded in the Initializer object, without knowing the shape and dtype of the variable being initialized.



In [3]:
# create ones tensor TensorFlow variable from the input

def ones_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))

ones_variable((2,2), tf.float32,  tf.ones_initializer())

ones_variable((2,3,5), tf.int32,  tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 3, 5) dtype=int32, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)>

#Create Zeros Tesnor using tf.zeros()
Creates a tensor with all elements set to zero (0)

In [4]:
# Creates a tensor with all elements set to zero.
zeros_2dt = tf.zeros((2,2), dtype=tf.int32)
zeros_2dt

zeros_3dt = tf.zeros((2,2,4), dtype=tf.int8)
zeros_3dt

zeros_3dt.shape

zeros_3dt.dtype

zeros_3dt.numpy()

zeros_3dt.numpy().tolist()

[[[0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0]]]

#Create Zeros Tesnor using tf.zeros_like()
Creates a tensor with all elements set to zero.

In [5]:
# Creates a tensor with all elements set to zero.

cont_2dt = tf.constant([[1,2,3],[4,5,6]])
cont_2dt

zl_2dt_from_cont = tf.zeros_like(cont_2dt)
zl_2dt_from_cont

var_2dt = tf.Variable([[1,2,3],[4,5,6]])
var_2dt

zl_2dt_from_var = tf.zeros_like(var_2dt, dtype=tf.bool)
zl_2dt_from_var

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False]])>

#Create Zeros Tesnor using tf.zeros_initializer() Initializer that generates tensors initialized to 0.

Initializers allow you to pre-specify an initialization strategy, encoded in the Initializer object, without knowing the shape and dtype of the variable being initialized.

In [6]:
def zeros_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))

zi_t_var= zeros_variable((2,2), tf.float32, tf.zeros_initializer())
zi_t_var

zeros_variable((3,2,5), tf.bool, tf.zeros_initializer())

tf.Variable(tf.zeros_initializer()((2,2), tf.float32))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>