#Programing Elements in TensorFlow 2.x

1. Constsnt
2. Variable
3. Placeholder
4. Sparse Vector

#Create Constant Tensor Using TensorFlow 2.0 Python

tf.constant(): Creates a constant tensor from a tensor-like object.

Syntax:

tf.constant(value, dtype=None, shape=None, name='Const')


Args:   
value: A constant value (or list) of output type `dtype`.   
dtype: The type of the elements of the resulting tensor.   
shape: Optional dimensions of resulting tensor.   
name: Optional name for the tensor.

Returns:   A Constant Tensor.
Note:

1. tf.Session() not in 2.x

2. Most of TensorFlow syntax same like Numpy

3. Use: While building neural network graph need constant varibale like input data,
it never change while training

**Create Constant Tensor in Different Way**

In [1]:
# Impost TensorFlow
import tensorflow as tf

In [2]:
# TensorFlow Version
tf.__version__

'2.15.0'

In [4]:
# Check GPU availability
tf.test.is_gpu_available()

False

In [6]:
# Create Integer Constant

a = tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
a.numpy()

10

In [8]:
# Create Float Constant
b = tf.constant(10.2)
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.2>

In [9]:
# Create String Constant
c = tf.constant("Indian Ai Production")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'Indian Ai Production'>

In [10]:
# Creat Bool Constant
d = tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [11]:
# Creat Constant Numpy array / List / Tuple
import numpy as np
np_array = tf.constant(np.array([1,2,3,4]))
np_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [12]:
# Create 1D constant
t_1d = tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [13]:
# Create 2D constant
t_2d = tf.constant([[1,2],[3,4]])
t_2d


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [14]:
# Access constant value
t_1d.numpy()

t_1d.numpy()[2]

3